/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AnnouncementDialog: typeof import('./src/components/AnnouncementDialog.vue')['default']
    ApiConfig: typeof import('./src/components/ApiConfig.vue')['default']
    ArticleStats: typeof import('./src/components/ArticleStats.vue')['default']
    BackupManager: typeof import('./src/components/BackupManager.vue')['default']
    ChapterManager: typeof import('./src/components/ChapterManager.vue')['default']
    CorpusManager: typeof import('./src/components/CorpusManager.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StorylineGantt: typeof import('./src/components/StorylineGantt.vue')['default']
    SummaryGenerator: typeof import('./src/components/SummaryGenerator.vue')['default']
    TemplateManager: typeof import('./src/components/TemplateManager.vue')['default']
    WriterChapterPanel: typeof import('./src/components/writer/WriterChapterPanel.vue')['default']
    WriterCharacterPanel: typeof import('./src/components/writer/WriterCharacterPanel.vue')['default']
    WriterCorpusPanel: typeof import('./src/components/writer/WriterCorpusPanel.vue')['default']
    WriterEditor: typeof import('./src/components/writer/WriterEditor.vue')['default']
    WriterEventPanel: typeof import('./src/components/writer/WriterEventPanel.vue')['default']
    WriterTabsBar: typeof import('./src/components/writer/WriterTabsBar.vue')['default']
    WriterTitleBar: typeof import('./src/components/writer/WriterTitleBar.vue')['default']
    WriterWorldviewPanel: typeof import('./src/components/writer/WriterWorldviewPanel.vue')['default']
    WritingGoals: typeof import('./src/components/WritingGoals.vue')['default']
    WritingTools: typeof import('./src/components/WritingTools.vue')['default']
  }
}
