// 所有localStorage key的唯一定义点
export const STORAGE_KEYS = {
  API_CONFIG: 'yunshu_api_config',
  THEME: 'yunshu_theme',
  NOVELS: 'yunshu_novels',
  CHAPTERS: 'yunshu_chapters',
  PROMPTS: 'yunshu_prompts',
  GENRES: 'yunshu_genres',
  WRITING_GOALS: 'yunshu_writing_goals',
  TOKEN_USAGE: 'yunshu_token_usage',
  BILLING_RECORDS: 'yunshu_billing_records',
  ACCOUNT_BALANCE: 'yunshu_account_balance',
  CUSTOM_TEMPLATES: 'yunshu_custom_templates',
  SHORT_STORY_CONFIG: 'yunshu_short_story_config',
  CHAPTER_SUMMARY_PROMPT: 'yunshu_chapter_summary_prompt',
  AUTO_BACKUP_SETTINGS: 'yunshu_auto_backup_settings',
  BACKUP_LIST: 'yunshu_backup_list',
  ANNOUNCEMENT_VERSION: 'yunshu_last_announcement_version',
  ANNOUNCEMENT_DATE: 'yunshu_last_announcement_date',
  FORESHADOWINGS: 'yunshu_foreshadowings',
  FRAGMENTS: 'yunshu_fragments',
  IDEA_BOARD: 'yunshu_idea_board',
  ACHIEVEMENTS: 'yunshu_achievements',
  GAMIFICATION_DATA: 'yunshu_gamification_data',
  PLUGIN_CONFIGS: 'yunshu_plugin_configs',
  PROVIDER_CONFIGS: 'yunshu_provider_configs',
  ACTIVE_PROVIDER: 'yunshu_active_provider',
  RECENT_PROJECTS: 'yunshu_recent_projects',
  // 新增：统一替代旧的无前缀key
}
